name: easy_file_saver
description: "Flutter plugin to easily save file to various storage directories."
version: 1.1.0
homepage: https://github.com/devresaja/easy_file_saver

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.4.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.resdev.easy_file_saver
        pluginClass: EasyFileSaverPlugin

